### ISSUE TITLE
Agenda items opening at the bottom of the page

### ISSUE THREAD

**Issue by rskoenig** [civinomics/city-council#123]
I click on an agenda item from a meeting page.
When the agenda item page opens, the item itself is cut off and my window is on the bottom of the page.

<img width="1280" alt="screen shot 2017-05-09 at 2 31 40 pm" src="https://cloud.githubusercontent.com/assets/4564957/25873713/61e2253c-34c4-11e7-938d-0de95e411485.png">

**Comment by drew-moore** [comment]
This is likely because you were scrolled to that position on the page when you closed  Chrome previously, so it remembers the position and takes you back there. You can confirm by loading arbitrary item pages in an incognito window - if it happens there, this is a (super weird, probably ng-material-related) bug. If not, then what you've observed is browser behavior that we can't do anything about.
